### ISSUE TITLE
test on npd benchmark

### ISSUE THREAD

**Issue by ghxiao** [oeg-upm/morph-rdb#11]
Hi, 

I am trying to use morph (latest 3.5.3 version) over the npd benchmark (https://github.com/ontop/npd-benchmark). 

- The r2rml mapping file is https://github.com/ontop/npd-benchmark/blob/master/mappings/mysql/spatial/npd-v2-ql_a.pretty.ttl

- The SPARQL query is 
https://github.com/ontop/npd-benchmark/blob/master/queries/01.q

And I got the following error message:
```
2015-01-08 11:28:16 ERROR R2RMLRunner:76 - Exception occured: Illegal repetition near index 41
<http://sws.ifi.uio.no/data/npd-v2/survey/{seaMultiline.seaSurveyName}/multiline>
```
The complete log is 

https://gist.github.com/ghxiao/4db2f62f38a6b853220c

Could you help to figure out what's the problem?

Btw, I also tested the master branch, which reports a different error:

```
INFO [main] (MorphBaseRunnerFactory.scala:95) - Building query translator...
 WARN [main] (MorphBaseRunnerFactory.scala:104) - Error building query translator!es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslatorFactory
Exception in thread "main" java.util.NoSuchElementException: None.get
# ...
# ...
2015-01-08 11:41:18 ERROR R2RMLRunner:76 - Exception occured: None.get
	at scala.None$.get(Option.scala:322)
	at scala.None$.get(Option.scala:320)
	at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner$$anonfun$1.apply(MorphBaseRunner.scala:186)
	at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner$$anonfun$1.apply(MorphBaseRunner.scala:184)
```

Thanks in advance!

**Comment by fpriyatna** [comment]
Thank you for reporting this. Is it possible to have the database schema in SQL file, just to make the debugging process easier?

**Comment by ghxiao** [comment]
The sql file is here:

https://github.com/ontop/npd-benchmark/tree/master/data/mysql/spatial

The smallest one is npd-data-dump.sql.7z

**Comment by JensPiegsa** [comment]
It seems like I hit the same error. Unfortunately I could not provide a database dump at this time. Are there any further investigations / insights on this?

	[...]
	DEBUG [main] (MorphDatabaseMetaData.scala:11) - Database MetaData created: nc_dd
	 DEBUG [main] (R2RMLTriplesMap.scala:27) - Building metadata for TriplesMap: TriplesMap1
	 DEBUG [main] (MorphBaseRunnerFactory.scala:108) - Building query translator...
	  WARN [main] (MorphBaseRunnerFactory.scala:117) - Error building query translator!es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslatorFactory
	 DEBUG [main] (MorphBaseRunner.scala:138) - sparql query = PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
	PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>

	SELECT  (count(*) AS ?no)
	WHERE
	  { ?s ?p ?o }

	 DEBUG [main] (MorphBaseRunner.scala:185) - SPARQL Query = 
	PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
	PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>

	SELECT  (count(*) AS ?no)
	WHERE
	  { ?s ?p ?o }

	 ERROR [main] (MorphRDBRunner.scala:78) - Exception occured: None.get
	 Exception in thread "main" java.util.NoSuchElementException: None.get
		at scala.None$.get(Option.scala:322)
		at scala.None$.get(Option.scala:320)
		at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner$$anonfun$1.apply(MorphBaseRunner.scala:186)
		at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner$$anonfun$1.apply(MorphBaseRunner.scala:184)
		at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
		at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
		at scala.collection.immutable.List.foreach(List.scala:381)
		at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
		at scala.collection.immutable.List.map(List.scala:284)
		at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner.translateSPARQLQueriesIntoSQLQueries(MorphBaseRunner.scala:184)
		at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner.run(MorphBaseRunner.scala:166)
		at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner$.main(MorphRDBRunner.scala:74)
		at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner.main(MorphRDBRunner.scala)

**Comment by dachafra** [comment]
I assume that the mapping is here now: https://github.com/ontop/npd-benchmark/tree/master/mappings/mysql/ontopv3/r2rml

We will test it with new version of the engine and see if it is resolved
