### ISSUE TITLE
Invalid SQL syntax 

### ISSUE THREAD

**Issue by cabadol** [oeg-upm/morph-rdb#12]
It looks like the *sql* query generated from a *Sparql* query has invalid syntax:  
```
2015-01-12 08:39:04,894 [main] INFO  es.upm.fi.dia.oeg.morph.base.DBUtility$ - Executing query: SELECT device.model AS "modelName",device.manufacturer AS "manufacturerName",268877525 AS "mappingid_modelName",1415843874 AS "mappingid_manufacturerName"
FROM T_METS_DEVICE device,  ( SELECT device.manufacturer  AS "manufacturer"
FROM T_METS_DEVICE device
group by manufacturer
 ) v_5544 ON ((device.manufacturer = v_5544.manufacturer) AND (v_5544.manufacturer IS NOT NULL) AND (device.model IS NOT NULL) AND (device.manufacturer = v_5544.manufacturer))
,  ( SELECT device.id  AS "id",device.serial  AS "serial",device.name  AS "name",device.description  AS "description",device.ip  AS "ip",device.domain  AS "domain",device.disposition  AS "disposition",device.exposure  AS "exposure",device.status  AS "status",device.model  AS "model",device.latitude  AS "latitude",device.longitude  AS "longitude",device.elevation  AS "elevation"
FROM T_METS_DEVICE device
 ) v_3444 ON (((v_3444.serial IS NOT NULL) AND (datastream.device_id = v_3444.id)) AND (device.model IS NOT NULL))
,  ( SELECT device.model  AS "model",device.manufacturer  AS "manufacturer"
FROM T_METS_DEVICE device
group by model
 ) v_7335 ON ((((v_7335.manufacturer IS NOT NULL) AND (v_7335.model IS NOT NULL) AND (device.model = v_7335.model)) AND ((device.manufacturer = v_7335.manufacturer) AND (device.model = v_7335.model))) AND (device.model IS NOT NULL))
WHERE device.manufacturer IS NOT NULL

2015-01-12 08:39:04,908 [main] ERROR R2RMLRunner - Exception occured: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ON ((device.manufacturer = v_5544.manufacturer) AND (v_5544.manufacturer IS NOT ' at line 5
Exception in thread "main" com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ON ((device.manufacturer = v_5544.manufacturer) AND (v_5544.manufacturer IS NOT ' at line 5
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2618)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2568)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:842)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:681)
	at es.upm.fi.dia.oeg.morph.base.DBUtility$.execute(DBUtility.scala:71)
	at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBDataSourceReader.execute(MorphRDBDataSourceReader.scala:19)
	at es.upm.fi.dia.oeg.morph.base.querytranslator.engine.QueryResultTranslator$$anonfun$translateResult$1.apply(QueryResultTranslator.scala:25)
	at es.upm.fi.dia.oeg.morph.base.querytranslator.engine.QueryResultTranslator$$anonfun$translateResult$1.apply(QueryResultTranslator.scala:21)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at es.upm.fi.dia.oeg.morph.base.querytranslator.engine.QueryResultTranslator.translateResult(QueryResultTranslator.scala:21)
	at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner.run(MorphBaseRunner.scala:171)
	at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner$.main(MorphRDBRunner.scala:72)
	at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner.main(MorphRDBRunner.scala)
```  

Logical tables are defined as *sql* queries in the R2RML file:    
```
<TriplesMapProductManufacturer>
  a rr:TriplesMap;
        
  rr:logicalTable [ 
        rr:sqlQuery  """SELECT device.manufacturer manufacturer FROM T_METS_DEVICE device GROUP BY manufacturer""" 
    ];
  
  rr:subjectMap [    
    a rr:Subject;
    rr:template "http://linkeddata.metscale.es/resource/Manufacturer/{manufacturer}";
    rr:termType rr:IRI;
    rr:class s:Organization;
  ];     

  rr:predicateObjectMap [ 
    rr:predicateMap [ rr:constant s:name ]; 
    rr:objectMap    [ rr:column "manufacturer"; rr:termType rr:Literal; ]; 
  ]; 
.

<TriplesMapProductModel>
  a rr:TriplesMap;
        
  rr:logicalTable [
        rr:sqlQuery  """SELECT device.model model, device.manufacturer manufacturer FROM T_METS_DEVICE device GROUP BY model""" 
    ];
  
  rr:subjectMap [    
    a rr:Subject;
    rr:template "http://linkeddata.metscale.es/resource/Manufacturer/{manufacturer}/Model/{model}";
    rr:termType rr:IRI;
    rr:class s:ProductModel;
  ];

  rr:predicateObjectMap [ 
    rr:predicateMap [ rr:constant s:name ]; 
    rr:objectMap    [ rr:column "model"; rr:termType rr:Literal; ]; 
  ];

  rr:predicateObjectMap [ 
    rr:predicateMap [ rr:constant s:manufacturer ]; 
    rr:objectMap    [ 
       rr:parentTriplesMap <TriplesMapProductManufacturer>;
       rr:joinCondition [ rr:child "manufacturer" ; rr:parent "manufacturer" ; ]
    ];
  ];        
.
``` 

And the SPARQL query is:  
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX iec: <http://linkeddata.metscale.es/ontology/IndustrialEnergyConsumption#>
PREFIX s: <http://schema.org/>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT ?sensorName ?modelName ?manufacturerName
WHERE {
	?sensor a iec:PowerAnalyzer_ActiveEnergy .
	?sensor ssn:onPlatform ?platform .
	?platform s:model ?model .
	?model s:manufacturer ?manufacturer .
	?model s:name ?modelName .
	?manufacturer s:name ?manufacturerName
}

```

/cc @fpriyatna @ocorcho

**Comment by fpriyatna** [comment]
Can you please also put the database schema?

**Comment by cabadol** [comment]
I'm afraid I can not publish it, it is private.

**Comment by dachafra** [comment]
It is impossible to test it with the latest version of the engine as we don't have access to the schema of the database. 
We will test SQL views in the updated version, where the problem should be
Issue closed
