### ISSUE TITLE
Exception on extend

### ISSUE THREAD

**Issue by eugenesiow** [oeg-upm/morph-rdb#24]
Hi,

This is my query:

``` sql
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX iotsn: <http://iot.soton.ac.uk/smarthome/sensor#>
PREFIX iot: <http://purl.oclc.org/NET/iot#>

SELECT (avg(?val) as ?sval) ?hours
WHERE {
  ?instant time:inXSDDateTime ?date.
  ?obs ssn:observationSamplingTime ?instant;
    ssn:observedBy iotsn:environmental1;
    ssn:observationResult ?snout.
  ?snout ssn:hasValue ?obsval.
  ?obsval a iot:InternalTemperatureValue;
    iot:hasQuantityValue ?val.
  FILTER (?date > "2012-07-20T00:00:00"^^xsd:dateTime && ?date < "2012-07-21T00:00:00"^^xsd:dateTime)
} GROUP BY (hours(xsd:dateTime(?date)) as ?hours)
```

I suspect somethings gone wrong in between the extend and project ops using Jena. I'm using morph v3.5.16.

This is the error message:

```
ERROR [main] (MorphRDBRunner.scala:76) - Exception occured: (extend ((?sval ?.0))
  (group ((?hours (hours (<http://www.w3.org/2001/XMLSchema#dateTime> ?date)))) ((?.0 (avg ?val)))
    (filter (&& (> ?date "2012-07-20T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>) (< ?date "2012-07-21T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>))
      (bgp
        (triple ?instant <http://www.w3.org/2006/time#inXSDDateTime> ?date)
        (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observationSamplingTime> ?instant)
        (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observedBy> <http://iot.soton.ac.uk/smarthome/sensor#environmental1>)
        (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observationResult> ?snout)
        (triple ?snout <http://purl.oclc.org/NET/ssnx/ssn#hasValue> ?obsval)
        (triple ?obsval <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.oclc.org/NET/iot#InternalTemperatureValue>)
        (triple ?obsval <http://purl.oclc.org/NET/iot#hasQuantityValue> ?val)
      ))))
 (of class com.hp.hpl.jena.sparql.algebra.op.OpExtend)
Exception in thread "main" scala.MatchError: (extend ((?sval ?.0))
  (group ((?hours (hours (<http://www.w3.org/2001/XMLSchema#dateTime> ?date)))) ((?.0 (avg ?val)))
    (filter (&& (> ?date "2012-07-20T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>) (< ?date "2012-07-21T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>))
      (bgp
        (triple ?instant <http://www.w3.org/2006/time#inXSDDateTime> ?date)
        (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observationSamplingTime> ?instant)
        (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observedBy> <http://iot.soton.ac.uk/smarthome/sensor#environmental1>)
        (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observationResult> ?snout)
        (triple ?snout <http://purl.oclc.org/NET/ssnx/ssn#hasValue> ?obsval)
        (triple ?obsval <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.oclc.org/NET/iot#InternalTemperatureValue>)
        (triple ?obsval <http://purl.oclc.org/NET/iot#hasQuantityValue> ?val)
      ))))
 (of class com.hp.hpl.jena.sparql.algebra.op.OpExtend)
    at es.upm.fi.dia.oeg.morph.base.querytranslator.engine.MorphMappingInferrer.genericInferBGP(MorphMappingInferrer.scala:51)
    at es.upm.fi.dia.oeg.morph.base.querytranslator.engine.MorphMappingInferrer.genericInferBGP(MorphMappingInferrer.scala:70)
    at es.upm.fi.dia.oeg.morph.base.querytranslator.engine.MorphMappingInferrer.genericInfer(MorphMappingInferrer.scala:85)
    at es.upm.fi.dia.oeg.morph.base.querytranslator.engine.MorphMappingInferrer.inferByRDFType(MorphMappingInferrer.scala:148)
    at es.upm.fi.dia.oeg.morph.base.querytranslator.engine.MorphMappingInferrer.infer(MorphMappingInferrer.scala:100)
    at es.upm.fi.dia.oeg.morph.base.querytranslator.MorphBaseQueryTranslator.translate(MorphBaseQueryTranslator.scala:1366)
    at es.upm.fi.dia.oeg.morph.base.querytranslator.MorphBaseQueryTranslator.translate(MorphBaseQueryTranslator.scala:1429)
    at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner$$anonfun$1.apply(MorphBaseRunner.scala:186)
    at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner$$anonfun$1.apply(MorphBaseRunner.scala:184)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.immutable.List.map(List.scala:284)
    at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner.translateSPARQLQueriesIntoSQLQueries(MorphBaseRunner.scala:184)
    at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunner.run(MorphBaseRunner.scala:166)
    at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner$.main(MorphRDBRunner.scala:72)
    at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner.main(MorphRDBRunner.scala)
```

Thanks!

**Comment by fpriyatna** [comment]
Thanks for reporting this, Eugene.
Could you please attach the R2RML mappings?

**Comment by eugenesiow** [comment]
Hi Freddy, thanks for the prompt reply. Here is the R2RML file.

[smarthome_environment.txt](https://github.com/oeg-upm/morph-rdb/files/210004/smarthome_environment.txt)

**Comment by dachafra** [comment]
Test it and see if it is solved in the latest version of the engine

**Comment by jatoledo** [comment]
Hi, 
I need more information. I can't see this bug in my test
```log
 1027 [main] DEBUG es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunnerFactory  - query = PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  iotsn: <http://iot.soton.ac.uk/smarthome/sensor#>
PREFIX  time: <http://www.w3.org/2006/time#>
PREFIX  ssn:  <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX  iot:  <http://purl.oclc.org/NET/iot#>

SELECT  (AVG(?val) AS ?sval) ?hours
WHERE
  { ?instant  time:inXSDDateTime    ?date .
    ?obs      ssn:observationSamplingTime  ?instant ;
              ssn:observedBy        iotsn:environmental1 ;
              ssn:observationResult  ?snout .
    ?snout    ssn:hasValue          ?obsval .
    ?obsval   a                     iot:InternalTemperatureValue ;
              iot:hasQuantityValue  ?val
    FILTER ( ( ?date > "2012-07-20T00:00:00"^^xsd:dateTime ) && ( ?date < "2012-07-21T00:00:00"^^xsd:dateTime ) )
  }
GROUP BY (hours(xsd:dateTime(?date)) AS ?hours)

1037 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - opSparqlQuery = (project (?sval ?hours)
  (extend ((?sval ?.0))
    (group ((?hours (hours (<http://www.w3.org/2001/XMLSchema#dateTime> ?date)))) ((?.0 (avg ?val)))
      (filter (&& (> ?date "2012-07-20T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>) (< ?date "2012-07-21T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>))
        (bgp
          (triple ?instant <http://www.w3.org/2006/time#inXSDDateTime> ?date)
          (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observationSamplingTime> ?instant)
          (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observedBy> <http://iot.soton.ac.uk/smarthome/sensor#environmental1>)
          (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observationResult> ?snout)
          (triple ?snout <http://purl.oclc.org/NET/ssnx/ssn#hasValue> ?obsval)
          (triple ?obsval <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.oclc.org/NET/iot#InternalTemperatureValue>)
          (triple ?obsval <http://purl.oclc.org/NET/iot#hasQuantityValue> ?val)
        )))))

1072 [main] INFO es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  -
this.mapInferredTypes = ?obsval -> Set(TripleMap3)
?obs -> Set(TripleMap0)
?instant -> Set(TripleMap1)
?snout -> Set(TripleMap2)
1074 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - opSparqlQueryRewritten =
(project (?sval ?hours)
  (extend ((?sval ?.0))
    (group ((?hours (hours (<http://www.w3.org/2001/XMLSchema#dateTime> ?date)))) ((?.0 (avg ?val)))
      (filter (&& (> ?date "2012-07-20T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>) (< ?date "2012-07-21T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>))
        (bgp
          (triple ?instant <http://www.w3.org/2006/time#inXSDDateTime> ?date)
          (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observationSamplingTime> ?instant)
          (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observedBy> <http://iot.soton.ac.uk/smarthome/sensor#environmental1>)
          (triple ?obs <http://purl.oclc.org/NET/ssnx/ssn#observationResult> ?snout)
          (triple ?snout <http://purl.oclc.org/NET/ssnx/ssn#hasValue> ?obsval)
          (triple ?obsval <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.oclc.org/NET/iot#InternalTemperatureValue>)
          (triple ?obsval <http://purl.oclc.org/NET/iot#hasQuantityValue> ?val)
        )))))

1076 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - entering transJoin
1085 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBPRSQLGenerator  - prSQLResult = es.upm.fi.dia.oeg.morph.base.querytranslator.MorphPRSQLResult@12bcd0c0
1085 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBCondSQLGenerator  - Generating genCondSQLPredicateObject for tp: ?instant @http://www.w3.org/2006/time#inXSDDateTime ?date
1091 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - entering transJoin
1098 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBCondSQLGenerator  - Generating genCondSQLPredicateObject for tp: ?obs @http://purl.oclc.org/NET/ssnx/ssn#observationSamplingTime ?instant
1100 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBCondSQLGenerator  - Generating genCondSQLPredicateObject for tp: ?obs @http://purl.oclc.org/NET/ssnx/ssn#observedBy http://iot.soton.ac.uk/smarthome/sensor#environmental1
1100 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBCondSQLGenerator  - Generating CondSQL for ConstantTermMap
1100 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBCondSQLGenerator  - Generating genCondSQLPredicateObject for tp: ?obs @http://purl.oclc.org/NET/ssnx/ssn#observationResult ?snout
1101 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - entering transJoin
1101 [main] ERROR es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBAlphaGenerator  - Multiple mappings of a predicate is not supported.
1101 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - InsatisfiableSQLExpression for tp: ?snout @http://purl.oclc.org/NET/ssnx/ssn#hasValue ?obsval
1102 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBCondSQLGenerator  - Generating genCondSQLPredicateObject for tp: ?obsval @http://purl.oclc.org/NET/iot#hasQuantityValue ?val
1109 [main] INFO es.upm.fi.dia.oeg.morph.base.sql.SQLQuery$  - leftTableFromItem = environment v_30548
1114 [main] INFO es.upm.fi.dia.oeg.morph.base.sql.SQLQuery$  - rightTable joinTable = INNER JOIN environment v_62946 ON (1 = 1)
1122 [main] INFO es.upm.fi.dia.oeg.morph.base.sql.SQLQuery$  - leftTableFromItem = environment v_31798
1127 [main] INFO es.upm.fi.dia.oeg.morph.base.sql.SQLQuery$  - rightTable joinTable = INNER JOIN environment v_30548 ON ('http://iot.soton.ac.uk/smarthome/sensor#environmental1' = 'http://iot.soton.ac.uk/smarthome/sensor#environmental1')
1127 [main] INFO es.upm.fi.dia.oeg.morph.base.sql.SQLQuery$  - rightTable joinTable = INNER JOIN environment v_62946 ON ((1 = 1) AND ('http://iot.soton.ac.uk/smarthome/sensor#environmental1' = 'http://iot.soton.ac.uk/smarthome/sensor#environmental1'))
1127 [main] DEBUG es.upm.fi.dia.oeg.morph.base.sql.SQLQuery  - mappingid_instant already selected
1127 [main] DEBUG es.upm.fi.dia.oeg.morph.base.sql.SQLQuery  - var_instant already selected
1129 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - expr is function
1129 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - expr is function
1129 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - expr is var
1129 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - expr is constant
1130 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - expr is function
1130 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - expr is var
1130 [main] DEBUG es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - expr is constant
1136 [main] INFO es.upm.fi.dia.oeg.morph.rdb.querytranslator.MorphRDBQueryTranslator  - Query translation time = 108 ms.
1137 [main] INFO es.upm.fi.dia.oeg.morph.base.DBUtility$  - Executing query ...
1137 [main] INFO es.upm.fi.dia.oeg.morph.base.DBUtility$  - Executing query:
```

In my test, I use the last version of morph. Please could you test with la last version? [https://github.com/oeg-upm/morph-rdb/releases](url)

**Comment by dachafra** [comment]
seems that the issue is solved
