### ISSUE TITLE
Received error while using generator.

### ISSUE THREAD

**Issue by gigialmo88** [oeg-upm/morph-rdb#27]
Hello,
I am trying to generate mappings for a given ttl file. I edited the batch.r2rml.properties file as such:

mappingdocument.file.path=TriplesMap_City.ttl
output.file.path=batch-result.nt
# RDF/XML|RDF/XML-ABBREV|N-TRIPLE|TURTLE|N3

output.rdflanguage=N-TRIPLE

no_of_database=1
database.name[0]=xxxx
database.driver[0]=com.mysql.jdbc.Driver
database.url[0]=jdbc:mysql://127.0.0.1:3306/xxxx
database.user[0]=xxxx
database.pwd[0]=xxxx
database.type[0]=mysql

and received the following error after running ./batch.bat 

```
java -cp morph.jar;lib/* es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner examples  batch.r2rml.properties
```

java.lang.NoClassDefFoundError: scala/Option
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: scala.Option
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"

The links within the ttl file are broken, so I don't know if this is related to that or not. Any suggestions?

Thanks!
Georgia

**Comment by dachafra** [comment]
Sorry for the late response. Please could you explain what "I am trying to generate mappings for a given ttl file." means?

**Comment by dachafra** [comment]
no answer after one week, and impossible to reproduce the example without the specific resources. It also seems that there is a problem with the installation of the engine. Documentation has been improved.

issue closed
