### ISSUE TITLE
log4j.properties file error

### ISSUE THREAD

**Issue by sebastianfelipe** [oeg-upm/morph-rdb#29]
There is a problem related with some missing file, I assume this file is this one [https://github.com/oeg-upm/morph-rdb/blob/master/morph-base/src/main/scala/es/upm/fi/dia/oeg/morph/base/MorphProperties.scala](url) around line 87. It needs the configurator file. I don't know if that is the solution, but please have a look at it. Here is the error:

 INFO [main](MorphProperties.scala:87) - reading configuration file : project/run.r2rml.properties
log4j:ERROR Could not read configuration file [log4j.properties].
java.io.FileNotFoundException: log4j.properties (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:306)
    at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:324)
    at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunnerFactory.<init>(MorphBaseRunnerFactory.scala:27)
    at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunnerFactory.<init>(MorphRDBRunnerFactory.scala:22)
    at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphCSVRunnerFactory.<init>(MorphCSVRunnerFactory.scala:19)
    at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphCSVRunner$.apply(MorphCSVRunner.scala:34)
    at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphCSVRunner$.apply(MorphCSVRunner.scala:42)
    at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphCSVRunner$.main(MorphCSVRunner.scala:60)
    at es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphCSVRunner.main(MorphCSVRunner.scala)
log4j:ERROR Ignoring configuration file [log4j.properties].
![screenshot 2016-10-07 23 37 49](https://cloud.githubusercontent.com/assets/6192023/19209799/9e4ed9d6-8ce8-11e6-8530-b44d6f562495.png)

I'm using El Capitan OSX and java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

I can't generate the output while this error exists.

Thanks.

**Comment by fpriyatna** [comment]
hi Sebastian, thanks for your interest on morph-rdb and forgive my late response.

The lack of the log.properties file does not affect the functionalities of morph-rdb. You can find the example of log4j.properties here: https://github.com/oeg-upm/morph-rdb/blob/master/morph-examples/log4j.properties and put that file in your active directory.

Please let me know if you need further assistance.

**Comment by goknurbati** [comment]
Hi Fpriyatna,
How can we add the log4j.properties file and this file has default content, or how can we edit it.
Thanks for your assist.

**Comment by fpriyatna** [comment]
Hi goknurbati,

You can add this log4j.properties file in the root folder of morph-rdb.

Regards
Freddy

**Comment by goknurbati** [comment]
Hi fpriyatna,
Thanks for your answer, I fixed the problem with changing the location of the log4j.properties file. (src/log4j.properties)

Regards...

**Comment by dachafra** [comment]
issue solved.
